export const CONNECTIVITY_STATUS_CHANGED = 'CONNECTIVITY_STATUS_CHANGED';
export const USER_LOGEDIN = 'USER_LOGEDIN';
export const USER_LOGEDOUT = 'USER_LOGEDOUT';
export const SET_SIGNED_URL = 'SET_SIGNED_URL';
export const SET_FILE = 'SET_FILE';